spring:
  application:
    name: codepulse-backend
  datasource:
    url: jdbc:postgresql://localhost:5433/codepulse
    username: codepulse
    password: ${DB_PASSWORD:codepulse_local}
  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate     # Flyway owns the schema
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: 8081
  error:
    include-message: always

management:
  endpoint:
    health:
      show-details: always

jwt:
  access-token:
    secret: ${JWT_ACCESS_SECRET:dGhpcy1pcy1hLXZlcnktc2VjdXJlLWxvbmctc2VjcmV0LWtleS1mb3ItYWNjZXNzLXRva2Vu}
    expiry-seconds: 900
  refresh-token:
    secret: ${JWT_REFRESH_SECRET:dGhpcy1pcy1hLXZlcnktc2VjdXJlLWxvbmctc2VjcmV0LWtleS1mb3ItcmVmcmVzaC10b2tlbg==}
    expiry-seconds: 604800       # 7 days

judge0:
  base-url: http://localhost:2358

springdoc:
  swagger-ui:
    path: /swagger-ui.html

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}

logging:
  pattern:
    level: "%5p [traceId=%X{traceId}]"
  level:
    com.codepulse: DEBUG
    org.flywaydb: DEBUG