spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/codepulse
    username: codepulse
    password: ${DB_PASSWORD}
  data:
    redis:
      host: redis
      port: 6379
      password: ${REDIS_PASSWORD:codepulse_redis_local}

jwt:
  access-token:
    secret: ${JWT_ACCESS_SECRET}
  refresh-token:
    secret: ${JWT_REFRESH_SECRET}
  cookie:
    secure: ${JWT_COOKIE_SECURE:false}

judge0:
  base-url: http://judge0-server:2358